--- #YAML:1.0
name: Net-Delicious
version: 0.99
author:
  - Aaron Straup Cope <ascope@cpan.org>
abstract: OOP for the del.icio.us API
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
