# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Delicious
version:      0.5
version_from: lib/Net/Delicious.pm
installdirs:  site
requires:
    HTTP::Request:                 0
    Log::Dispatch:                 2
    LWP::UserAgent:                0
    Test::More:                    0
    XML::Simple:                   2
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
